# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ziheng
tagline:          ''
description:      ''
url:              https://zihengzzh.github.io
baseurl:          /
about:            
posts:            
projects:

author:
  name:           'Ziheng Zhang'
  url:            https://zihengzzh.github.io

paginate:         5

# Custom vars
version:          0.1.0

